#!/bin/sh -e
# A simple script to convert all TGA files to indexed PNG 1.0.3,
# Copyright (c) 2013 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.

# Derived from:
# http://www.gimptalk.com/index.php?/topic/
#		46715-batch-convert-xcf-to-png/page__p__354668#entry354668

# Variant: Upscale Image
# -> (gimp-image-scale image 1100 1442)
# Variant: Unsharp mask (radius, amount, threshold)
# -> (plug-in-unsharp-mask RUN-NONINTERACTIVE image layer 3.0 1.0 0.0)

indices=8

if [ "$1" = "--help" -o "$1" = "-h" ]; then
	echo "USAGE $0 [indices]"
	echo Converts all TGA files to indexed PNGs.
	exit 1
elif [ $# != 0 ]; then
	indices=$1
fi

gimp -n -i -d -f -b - > /dev/null <<EOF
(let* ( (file's (cadr (file-glob "*.tga" 1)))
					(filename "") (image 0) (layer 0) )
	(while (pair? file's) 
		(set! image (car (gimp-file-load RUN-NONINTERACTIVE
						(car file's) (car file's))))
		(set! layer (car (gimp-image-merge-visible-layers image
								CLIP-TO-IMAGE)))
		(gimp-image-convert-indexed image NO-DITHER MAKE-PALETTE
							$indices FALSE TRUE "")
		(set! filename (string-append (substring (car file's) 0
			(- (string-length (car file's)) 4)) "_indexed.png"))
		(gimp-file-save RUN-NONINTERACTIVE image layer filename
								filename)
		(gimp-image-delete image)
		(set! file's (cdr file's))
	)
	(gimp-quit 0)
)
EOF
