#!/bin/sh -e
# Ma_Sys.ma X 11 Device Enable/Disable Script 1.0.1,
# Copyright (c) 2014, 2018 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.

head -n 4 "$0" | tail -n 3 | cut -c 3-
echo

# cf. http://askubuntu.com/questions/65951/how-to-disable-touchpad

if [ $# != 2 -o "$1" = "--help" -o "$1" = "-h" ]; then
	echo "USAGE $(basename "$0") pattern 0|1"
	echo
	echo To list all potential devices use \`xinput list\`.
	echo To enable set to 1. To disable set to 0.
	exit 0
fi

id="$(xinput list | grep -F "$1" | tr ' \t' '\n' | grep -E '^id=' | cut -c 4-)"
echo Selected IDs: $id
for i in $id; do
	xinput set-prop "$i" "Device Enabled" "$2"
done
